# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

def dricom_pods
    # Pods for Dricom
    pod 'AlamofireImage', :git => 'https://github.com/avito-tech/AlamofireImage'
    pod 'Alamofire', :git => 'https://github.com/avito-tech/Alamofire'
    pod 'Unbox'
    pod 'KeychainAccess'
    pod 'CryptoSwift'
    pod 'Paparazzo/Core'
end
    
target 'Dricom' do
  dricom_pods
end

target 'DricomTests' do
    dricom_pods
end
